// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gh_encode_
StringVector gh_encode_(NumericVector latitude, NumericVector longitude, int precision);
RcppExport SEXP _geohashTools_gh_encode_(SEXP latitudeSEXP, SEXP longitudeSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type latitude(latitudeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type longitude(longitudeSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(gh_encode_(latitude, longitude, precision));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _geohash_tools_gh_encode_(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_geohashTools_gh_encode_", (DL_FUNC) &_geohashTools_gh_encode_, 3},
    {"_geohash_tools_gh_encode_", (DL_FUNC) &_geohash_tools_gh_encode_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_geohashTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
