# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gh_encode_ <- function(latitude, longitude, precision = 6L) {
    .Call(`_geohashTools_gh_encode_`, latitude, longitude, precision)
}

gh_decode_ <- function(ghs, include_delta, coord_loc) {
    .Call(`_geohashTools_gh_decode_`, ghs, include_delta, coord_loc)
}

